version: '1'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/backend
      - /usr/app/backend/node_modules
    ports:
      - "3001:3001"
   
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
 